export const RESET = "APP/RESET";
export const UPDATEPLAYERS = "PLAYER/UPDATEPLAYERS";
export const NEXTLEADER = "PLAYER/NEXTPLAYER";
export const UPDATEQUESTARR = "QUEST/UPDATEQUESTARR";
export const UPDATEQUESTRESULT = "QUEST/UPDATEQUESTRESULT";
export const PROCEEDQUEST = "QUEST/PROCEEDQUEST";

export default null;
